@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:koni_archive_core/koni_archive_core.dart';
import 'package:koni_tar/koni_tar.dart';
import 'package:test/test.dart';

/// Fixtures generated by `tool/generate_fixtures.dart` with bsdtar; see
/// test/fixtures/tar/fixtures_manifest.json for provenance.
Future<ArchiveReader> openFixture(String name) async {
  final bytes = File('test/fixtures/tar/$name').readAsBytesSync();
  return const TarFormat().openReader(
    MemoryByteSource(bytes),
    const ArchiveReadOptions(),
  );
}

Future<String> collectString(ArchiveReader reader, ArchiveEntry entry) async =>
    utf8.decode(
      (await reader.openRead(entry).toList()).expand<int>((c) => c).toList(),
    );

final fixedMtime = DateTime.utc(2020, 1, 2, 3, 4, 5);

void main() {
  group('basic_ustar.tar', () {
    test('lists the full entry model', () async {
      final reader = await openFixture('basic_ustar.tar');
      final paths = reader.entries.map((e) => e.path).toList();
      expect(paths, [
        'hello.txt',
        'empty.txt',
        'nested',
        'nested/deep',
        'nested/deep/data.bin',
        '日本語',
        '日本語/ページ001.txt',
        'link.txt',
        'hard.txt',
      ]);

      final byPath = {for (final e in reader.entries) e.path: e};
      final hello = byPath['hello.txt']!;
      expect(hello.type, ArchiveEntryType.file);
      expect(hello.uncompressedSize, 12);
      expect(hello.compressedSize, isNull, reason: 'tar records none (§4)');
      expect(hello.modified, fixedMtime);
      expect(hello.posixMode, isNotNull);
      expect(hello.posixMode! & 0x1FF, int.parse('644', radix: 8));
      expect(hello.compression, ArchiveCompression.stored);
      expect(hello.isEncrypted, isFalse);

      expect(byPath['empty.txt']!.uncompressedSize, 0);
      expect(byPath['nested']!.type, ArchiveEntryType.directory);
      expect(
        byPath['nested']!.path,
        'nested',
        reason: 'trailing slash dropped; type carries directory-ness',
      );

      final link = byPath['link.txt']!;
      expect(link.type, ArchiveEntryType.symlink);
      expect(link.linkTarget, 'hello.txt');

      final hard = byPath['hard.txt']!;
      expect(hard.type, ArchiveEntryType.hardlink);
      expect(hard.linkTarget, 'hello.txt');
    });

    test('streams file content', () async {
      final reader = await openFixture('basic_ustar.tar');
      final byPath = {for (final e in reader.entries) e.path: e};
      expect(
        await collectString(reader, byPath['hello.txt']!),
        'hello, tar!\n',
      );
      expect(await collectString(reader, byPath['empty.txt']!), '');

      final data =
          (await reader.openRead(byPath['nested/deep/data.bin']!).toList())
              .expand<int>((c) => c)
              .toList();
      expect(data, hasLength(2600));
      expect(
        data,
        List.generate(2600, (i) => (i * 7 + 3) & 0xFF),
        reason: 'content must be exact, not block-padded',
      );
    });

    test('symlinks are metadata only: content stream is empty (§7)', () async {
      final reader = await openFixture('basic_ustar.tar');
      final link = reader.entries.firstWhere(
        (e) => e.type == ArchiveEntryType.symlink,
      );
      expect(await collectString(reader, link), isEmpty);
    });
  });

  group('PAX and GNU long names', () {
    final longName = '${'L' * 160}.txt';
    final longTarget = 'T' * 150;

    for (final fixture in ['long_paths_pax.tar', 'long_paths_gnu.tar']) {
      test('$fixture resolves >100-char names and link targets', () async {
        final reader = await openFixture(fixture);
        final byPath = {for (final e in reader.entries) e.path: e};
        expect(byPath.keys, contains(longName));
        expect(byPath[longName]!.uncompressedSize, 18);
        expect(
          await collectString(reader, byPath[longName]!),
          'long name content\n',
        );
        expect(byPath['longlink.txt']!.type, ArchiveEntryType.symlink);
        expect(byPath['longlink.txt']!.linkTarget, longTarget);
      });
    }

    test('PAX unicode path round-trips', () async {
      final reader = await openFixture('long_paths_pax.tar');
      expect(reader.entries.map((e) => e.path), contains('日本語/ページ001.txt'));
    });
  });

  group('other formats and shapes', () {
    test('v7 (magic-less) tars parse via checksum validation', () async {
      final reader = await openFixture('v7.tar');
      expect(reader.entries.map((e) => e.path), ['hello.txt', 'empty.txt']);
      expect(
        await collectString(reader, reader.entries.first),
        'hello, tar!\n',
      );
    });

    test('FIFOs are represented, not materialized', () async {
      final reader = await openFixture('special_types.tar');
      final byPath = {for (final e in reader.entries) e.path: e};
      expect(byPath['pipe.fifo']!.type, ArchiveEntryType.fifo);
      // The entry after the fifo parses fine (no data blocks consumed).
      expect(
        await collectString(reader, byPath['hello.txt']!),
        'hello, tar!\n',
      );
    });

    test('duplicate paths are both listed in index order (§4)', () async {
      final reader = await openFixture('duplicate.tar');
      expect(reader.entries.map((e) => e.path), ['hello.txt', 'hello.txt']);
    });

    test('an empty archive lists no entries', () async {
      final reader = await openFixture('empty.tar');
      expect(reader.entries, isEmpty);
    });

    test('CBT comics list and stream', () async {
      final reader = await openFixture('synthetic_comic.cbt');
      final pages =
          reader.entries.where((e) => e.path.endsWith('.png')).toList();
      expect(pages, hasLength(3));
      final firstPage = (await reader.openRead(pages.first).toList())
          .expand<int>((c) => c);
      expect(firstPage.take(8), [
        0x89,
        0x50,
        0x4E,
        0x47,
        0x0D,
        0x0A,
        0x1A,
        0x0A,
      ]);
      expect(firstPage, hasLength(1032));
    });
  });

  group('detection against fixtures', () {
    test('every fixture is detected as tar', () async {
      const format = TarFormat();
      final dir = Directory('test/fixtures/tar');
      final tarFiles = dir.listSync().whereType<File>().where(
        (f) => f.path.endsWith('.tar') || f.path.endsWith('.cbt'),
      );
      expect(tarFiles, isNotEmpty);
      for (final file in tarFiles) {
        final source = MemoryByteSource(file.readAsBytesSync());
        expect(await format.matches(source), isTrue, reason: file.path);
      }
    });

    test('non-tar bytes are rejected', () async {
      const format = TarFormat();
      expect(
        await format.matches(
          MemoryByteSource(Uint8List.fromList(utf8.encode('PK\x03\x04zip?'))),
        ),
        isFalse,
      );
      final randomish = Uint8List.fromList(
        List.generate(2048, (i) => (i * 37 + 11) & 0xFF),
      );
      expect(await format.matches(MemoryByteSource(randomish)), isFalse);
    });
  });
}
