@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:koni_archive_core/koni_archive_core.dart';
import 'package:koni_gzip/koni_gzip.dart';
import 'package:test/test.dart';

/// Fixtures generated by `tool/generate_fixtures.dart` with gzip(1); see
/// test/fixtures/gzip/fixtures_manifest.json for provenance.
Uint8List fixtureBytes(String name) =>
    File('test/fixtures/gzip/$name').readAsBytesSync();

Future<ArchiveReader> openFixture(String name, {String? sourceName}) =>
    const GzipFormat().openReader(
      MemoryByteSource(fixtureBytes(name), name: sourceName),
      const ArchiveReadOptions(),
    );

Future<String> collectString(ArchiveReader reader, ArchiveEntry entry) async =>
    utf8.decode(
      (await reader.openRead(entry).toList()).expand<int>((c) => c).toList(),
    );

void main() {
  group('single-entry adapter', () {
    test('FNAME names the entry; metadata from header and trailer', () async {
      final reader = await openFixture('hello.txt.gz');
      final entry = reader.entries.single;
      expect(entry.path, 'hello.txt');
      expect(entry.type, ArchiveEntryType.file);
      expect(entry.modified, DateTime.utc(2020, 1, 2, 3, 4, 5));
      expect(entry.uncompressedSize, 13); // ISIZE
      expect(entry.compressedSize, fixtureBytes('hello.txt.gz').length);
      expect(entry.compression, ArchiveCompression.deflate);
      expect(entry.crc32, isNotNull);
      expect(await collectString(reader, entry), 'hello, gzip!\n');
    });

    test('without FNAME the name derives from the source name', () async {
      final reader = await openFixture(
        'anonymous.gz',
        sourceName: '/downloads/anonymous.gz',
      );
      final entry = reader.entries.single;
      expect(entry.path, 'anonymous');
      expect(entry.modified, isNull, reason: 'gzip -n: no mtime');
      expect(entry.uncompressedSize, 100000);
      final content =
          (await reader.openRead(entry).toList())
              .expand<int>((c) => c)
              .toList();
      expect(content, List.generate(100000, (i) => (i * 7 + i ~/ 1000) & 0xFF));
    });

    test('with neither FNAME nor a source name, the entry is "data"', () async {
      final reader = await openFixture('anonymous.gz');
      expect(reader.entries.single.path, 'data');
    });
  });

  group('multi-member', () {
    test('decodes to the concatenated content of all members', () async {
      final reader = await openFixture('multi_member.gz');
      final entry = reader.entries.single;
      expect(entry.path, 'hello.txt', reason: 'first member names the entry');
      expect(
        await collectString(reader, entry),
        'hello, gzip!\nsecond member content\n',
      );
    });
  });

  group('integrity', () {
    test(
      'a corrupted body surfaces as a typed error through the stream',
      () async {
        final bytes = fixtureBytes('hello.txt.gz');
        // Flip a bit in the deflate body (past the 20-byte header).
        bytes[22] ^= 0x10;
        final reader = await const GzipFormat().openReader(
          MemoryByteSource(bytes),
          const ArchiveReadOptions(),
        );
        await expectLater(
          reader.openRead(reader.entries.single).toList(),
          throwsA(isA<ArchiveException>()),
        );
      },
    );

    test(
      'a CRC mismatch is ChecksumMismatchException; opt-out skips it',
      () async {
        final bytes = fixtureBytes('hello.txt.gz');
        bytes[bytes.length - 5] ^= 0xFF; // stored CRC byte
        final verifying = await const GzipFormat().openReader(
          MemoryByteSource(bytes),
          const ArchiveReadOptions(),
        );
        await expectLater(
          verifying.openRead(verifying.entries.single).toList(),
          throwsA(isA<ChecksumMismatchException>()),
        );
        final lax = await const GzipFormat().openReader(
          MemoryByteSource(bytes),
          const ArchiveReadOptions(verifyChecksums: false),
        );
        expect(await collectString(lax, lax.entries.single), 'hello, gzip!\n');
      },
    );

    test('truncated files throw typed errors', () async {
      final bytes = fixtureBytes('hello.txt.gz');
      for (final cut in [5, 15, bytes.length - 4]) {
        final sliced = Uint8List.sublistView(bytes, 0, cut);
        Object? error;
        try {
          final reader = await const GzipFormat().openReader(
            MemoryByteSource(sliced),
            const ArchiveReadOptions(),
          );
          await reader.openRead(reader.entries.single).toList();
        } on Object catch (e) {
          error = e;
        }
        expect(error, isA<ArchiveException>(), reason: 'cut at $cut');
      }
    });
  });

  group('detection', () {
    test('gzip fixtures match; non-gzip bytes do not', () async {
      const format = GzipFormat();
      for (final name in ['hello.txt.gz', 'anonymous.gz', 'multi_member.gz']) {
        expect(
          await format.matches(MemoryByteSource(fixtureBytes(name))),
          isTrue,
          reason: name,
        );
      }
      expect(
        await format.matches(
          MemoryByteSource(Uint8List.fromList(List.filled(64, 0x50))),
        ),
        isFalse,
      );
    });
  });
}
