@TestOn('vm')
library;

import 'dart:io';
import 'dart:typed_data';

import 'package:koni_archive_core/koni_archive_core.dart';
import 'package:koni_tar/koni_tar.dart';
import 'package:koni_xz/koni_xz.dart';
// ignore: implementation_imports — precise offset math for a corruption test.
import 'package:koni_xz/src/xz_container.dart';
import 'package:test/test.dart';

/// Fixtures generated by `tool/generate_fixtures.dart` with xz(1); see
/// test/fixtures/xz/fixtures_manifest.json for provenance.
Uint8List fixtureBytes(String name) =>
    File('test/fixtures/xz/$name').readAsBytesSync();

Future<ArchiveReader> openFixture(
  String name, {
  String? sourceName,
  ArchiveReadOptions options = const ArchiveReadOptions(),
  List<ArchiveFormat> layered = const [],
}) => XzFormat(
  layeredFormats: layered,
).openReader(MemoryByteSource(fixtureBytes(name), name: sourceName), options);

Future<Uint8List> collect(ArchiveReader reader, ArchiveEntry entry) async {
  final b = BytesBuilder(copy: false);
  await for (final chunk in reader.openRead(entry)) {
    b.add(chunk);
  }
  return b.takeBytes();
}

void main() {
  final hello = fixtureBytes('hello.txt');
  final prose = fixtureBytes('prose.bin');
  final ramp = fixtureBytes('ramp.bin');

  group('integrity checks', () {
    for (final check in ['crc64', 'crc32', 'sha256', 'none']) {
      test('$check decodes to the plaintext', () async {
        final reader = await openFixture('hello_$check.xz');
        final entry = reader.entries.single;
        expect(entry.type, ArchiveEntryType.file);
        expect(entry.uncompressedSize, hello.length);
        expect(entry.compression, ArchiveCompression.lzma2);
        expect(await collect(reader, entry), hello);
        await reader.close();
      });
    }
  });

  group('entry naming', () {
    test('.xz is stripped from the source name', () async {
      final reader = await openFixture(
        'hello_crc64.xz',
        sourceName: '/downloads/comics.xz',
      );
      expect(reader.entries.single.path, 'comics');
      expect(reader.entries.single.modified, isNull); // xz stores no mtime
      await reader.close();
    });

    test('.txz maps to .tar', () async {
      final reader = await openFixture(
        'hello_crc64.xz',
        sourceName: 'book.txz',
      );
      expect(reader.entries.single.path, 'book.tar');
      await reader.close();
    });

    test('no source name falls back to "data"', () async {
      final reader = await openFixture('hello_crc64.xz');
      expect(reader.entries.single.path, 'data');
      await reader.close();
    });

    test('compressedSize is the whole container', () async {
      final reader = await openFixture('hello_crc64.xz');
      expect(
        reader.entries.single.compressedSize,
        fixtureBytes('hello_crc64.xz').length,
      );
      await reader.close();
    });
  });

  group('filters', () {
    test('delta reverses to the ramp', () async {
      final reader = await openFixture('ramp_delta.xz');
      expect(await collect(reader, reader.entries.single), ramp);
      await reader.close();
    });

    test('x86 BCJ reverses to the prose', () async {
      final reader = await openFixture('prose_bcj.xz');
      expect(await collect(reader, reader.entries.single), prose);
      await reader.close();
    });

    test('a two-transform chain (delta + x86) reverses correctly', () async {
      final reader = await openFixture('ramp_delta_x86.xz');
      expect(await collect(reader, reader.entries.single), ramp);
      await reader.close();
    });
  });

  group('block and stream structure', () {
    test('a multi-block stream decodes as one entry', () async {
      final reader = await openFixture('prose_multiblock.xz');
      expect(reader.entries, hasLength(1));
      expect(reader.entries.single.uncompressedSize, prose.length);
      expect(await collect(reader, reader.entries.single), prose);
      await reader.close();
    });

    test('multi-block with BCJ: the filter resets per block', () async {
      // Each block's x86 BCJ uses start offset 0 independently; a whole-stream
      // BCJ would corrupt every block after the first.
      final reader = await openFixture('prose_bcj_multiblock.xz');
      expect(await collect(reader, reader.entries.single), prose);
      await reader.close();
    });

    test('an empty .xz (zero blocks) decodes to nothing', () async {
      final reader = await openFixture('empty.xz');
      expect(reader.entries, hasLength(1));
      expect(reader.entries.single.uncompressedSize, 0);
      expect(await collect(reader, reader.entries.single), isEmpty);
      await reader.close();
    });

    test('concatenated streams decode as one entry', () async {
      // two_stream = hello_crc64 ++ hello_crc32, so the content is hello twice.
      final reader = await openFixture('two_stream.xz');
      expect(reader.entries, hasLength(1));
      final expected = Uint8List.fromList([...hello, ...hello]);
      expect(reader.entries.single.uncompressedSize, expected.length);
      expect(await collect(reader, reader.entries.single), expected);
      await reader.close();
    });
  });

  group('layered .tar.xz', () {
    test('opens as the inner TAR via the layered format', () async {
      final reader = await openFixture(
        'sample.tar.xz',
        sourceName: 'sample.tar.xz',
        layered: const [TarFormat()],
      );
      expect(reader.format.name, 'tar');
      final names = reader.entries.map((e) => e.path).toList();
      expect(names, containsAll(<String>['hello.txt', 'prose.bin']));
      await reader.close();
    });

    test('the single-entry adapter wins when the inner probe fails', () async {
      // hello_crc64 does not decompress to a TAR, so the layered format falls
      // back to presenting the .xz as one entry.
      final reader = await openFixture(
        'hello_crc64.xz',
        sourceName: 'hello_crc64.xz',
        layered: const [TarFormat()],
      );
      expect(reader.format.name, 'xz');
      expect(reader.entries, hasLength(1));
      expect(await collect(reader, reader.entries.single), hello);
      await reader.close();
    });
  });

  group('checksum verification', () {
    test('verifyChecksums:false still decodes', () async {
      final reader = await openFixture(
        'hello_crc64.xz',
        options: const ArchiveReadOptions(verifyChecksums: false),
      );
      expect(await collect(reader, reader.entries.single), hello);
      await reader.close();
    });

    test('a corrupted check surfaces as ChecksumMismatchException', () async {
      // Locate block 0's check field precisely and flip a byte in it, so the
      // LZMA2 payload still decodes but the integrity check fails.
      final bytes = fixtureBytes('hello_crc64.xz');
      final container = await parseXzContainer(MemoryByteSource(bytes));
      final block = container.blocks.single;
      final sizeByte = bytes[block.start];
      final headerSize = (sizeByte + 1) * 4;
      final compressedSize = block.unpaddedSize - headerSize - block.checkSize;
      final padding = roundUp4(compressedSize) - compressedSize;
      final checkOffset = block.start + headerSize + compressedSize + padding;
      final mutated = Uint8List.fromList(bytes);
      mutated[checkOffset] ^= 0xFF;

      final reader = await const XzFormat().openReader(
        MemoryByteSource(mutated),
        const ArchiveReadOptions(),
      );
      await expectLater(
        collect(reader, reader.entries.single),
        throwsA(isA<ChecksumMismatchException>()),
      );
      await reader.close();
    });

    test('a corrupted payload surfaces as a typed error', () async {
      final bytes = fixtureBytes('hello_crc64.xz');
      final mutated = Uint8List.fromList(bytes);
      // Flip a byte in the compressed data (just past the 12-byte header +
      // block header) to derail LZMA2 or fail the check.
      mutated[30] ^= 0xFF;
      final reader = await const XzFormat().openReader(
        MemoryByteSource(mutated),
        const ArchiveReadOptions(),
      );
      await expectLater(
        collect(reader, reader.entries.single),
        throwsA(isA<CorruptArchiveException>()),
      );
      await reader.close();
    });
  });

  group('typed errors', () {
    test('a non-x86 BCJ filter is unsupported', () async {
      final reader = await openFixture('prose_arm.xz');
      await expectLater(
        collect(reader, reader.entries.single),
        throwsA(isA<UnsupportedCompressionException>()),
      );
      await reader.close();
    });

    test('a reserved check id is rejected at open', () async {
      // Rewrite hello_none.xz's stream-footer check nibble to a reserved id
      // (0x02) and fix the footer CRC-32, so parsing reaches — and rejects —
      // the unsupported-check guard.
      final bytes = Uint8List.fromList(fixtureBytes('hello_none.xz'));
      final footer = bytes.length - 12;
      bytes[footer + 9] = 0x02; // stream-flags check id (byte 9 of the footer)
      final crc = Crc32.compute(
        Uint8List.sublistView(bytes, footer + 4, footer + 10),
      );
      bytes[footer + 0] = crc & 0xFF;
      bytes[footer + 1] = (crc >> 8) & 0xFF;
      bytes[footer + 2] = (crc >> 16) & 0xFF;
      bytes[footer + 3] = (crc >> 24) & 0xFF;
      expect(
        const XzFormat().openReader(
          MemoryByteSource(bytes),
          const ArchiveReadOptions(),
        ),
        throwsA(isA<InvalidHeaderException>()),
      );
    });

    test('truncation is a typed error', () async {
      final bytes = fixtureBytes('prose_bcj.xz');
      final truncated = Uint8List.sublistView(bytes, 0, bytes.length - 20);
      expect(
        const XzFormat().openReader(
          MemoryByteSource(truncated),
          const ArchiveReadOptions(),
        ),
        throwsA(isA<CorruptArchiveException>()),
      );
    });
  });

  group('decompression-bomb guards', () {
    test('maxEntrySize rejects a block over the limit', () async {
      final reader = await openFixture(
        'prose_bcj.xz',
        options: const ArchiveReadOptions(maxEntrySize: 1000),
      );
      await expectLater(
        collect(reader, reader.entries.single),
        throwsA(isA<SizeLimitExceededException>()),
      );
      await reader.close();
    });

    test('maxEntrySize at the exact size passes', () async {
      final reader = await openFixture(
        'prose_bcj.xz',
        options: ArchiveReadOptions(maxEntrySize: prose.length),
      );
      expect(await collect(reader, reader.entries.single), prose);
      await reader.close();
    });

    test('maxContainerDecodeSize caps a layered .tar.xz at open', () async {
      expect(
        XzFormat(layeredFormats: const [TarFormat()]).openReader(
          MemoryByteSource(
            fixtureBytes('sample.tar.xz'),
            name: 'sample.tar.xz',
          ),
          const ArchiveReadOptions(maxContainerDecodeSize: 100),
        ),
        throwsA(isA<SizeLimitExceededException>()),
      );
    });
  });
}
