@TestOn('vm')
library;

import 'dart:io';
import 'dart:typed_data';

import 'package:koni_archive_core/koni_archive_core.dart';
import 'package:koni_tar/koni_tar.dart';
import 'package:koni_zstd/koni_zstd.dart';
import 'package:test/test.dart';

/// Fixtures generated by `tool/generate_fixtures.dart` with zstd(1); see
/// test/fixtures/zstd/fixtures_manifest.json for provenance.
Uint8List fixtureBytes(String name) =>
    File('test/fixtures/zstd/$name').readAsBytesSync();

Future<ArchiveReader> openFixture(
  String name, {
  String? sourceName,
  ArchiveReadOptions options = const ArchiveReadOptions(),
  List<ArchiveFormat> layered = const [],
}) => ZstdFormat(
  layeredFormats: layered,
).openReader(MemoryByteSource(fixtureBytes(name), name: sourceName), options);

Future<Uint8List> collect(ArchiveReader reader, ArchiveEntry entry) async {
  final b = BytesBuilder(copy: false);
  await for (final chunk in reader.openRead(entry)) {
    b.add(chunk);
  }
  return b.takeBytes();
}

void main() {
  final hello = fixtureBytes('hello.txt');
  final prose = fixtureBytes('prose.bin');

  group('single-entry .zst', () {
    test('decodes with unknown size and zstd metadata', () async {
      final reader = await openFixture(
        'hello.zst',
        sourceName: '/downloads/hello.zst',
      );
      final entry = reader.entries.single;
      expect(entry.path, 'hello');
      expect(entry.type, ArchiveEntryType.file);
      expect(entry.compression, ArchiveCompression.zstd);
      expect(entry.uncompressedSize, -1);
      expect(entry.compressedSize, fixtureBytes('hello.zst').length);
      expect(await collect(reader, entry), hello);
      await reader.close();
    });

    test('name derivation: .tzst -> .tar, none -> data', () async {
      final a = await openFixture('hello.zst', sourceName: 'book.tzst');
      expect(a.entries.single.path, 'book.tar');
      await a.close();
      final b = await openFixture('hello.zst');
      expect(b.entries.single.path, 'data');
      await b.close();
    });
  });

  group('layered .tar.zst', () {
    test('opens as the inner TAR', () async {
      final reader = await openFixture(
        'sample.tar.zst',
        sourceName: 'sample.tar.zst',
        layered: const [TarFormat()],
      );
      expect(reader.format.name, 'tar');
      final names = reader.entries.map((e) => e.path).toList();
      expect(names, containsAll(<String>['hello.txt', 'prose.bin']));
      expect(
        await collect(
          reader,
          reader.entries.firstWhere((e) => e.path == 'prose.bin'),
        ),
        prose,
      );
      await reader.close();
    });

    test('falls back to the single entry when the inner probe fails', () async {
      final reader = await openFixture(
        'hello.zst',
        sourceName: 'hello.zst',
        layered: const [TarFormat()],
      );
      expect(reader.format.name, 'zstd');
      expect(await collect(reader, reader.entries.single), hello);
      await reader.close();
    });
  });

  group('guards and errors', () {
    test('maxEntrySize aborts an over-limit decode', () async {
      final reader = await openFixture(
        'sample.tar.zst',
        options: const ArchiveReadOptions(maxEntrySize: 100),
      );
      await expectLater(
        collect(reader, reader.entries.single),
        throwsA(isA<SizeLimitExceededException>()),
      );
      await reader.close();
    });

    test('maxContainerDecodeSize caps a layered .tar.zst at open', () async {
      await expectLater(
        ZstdFormat(layeredFormats: const [TarFormat()]).openReader(
          MemoryByteSource(
            fixtureBytes('sample.tar.zst'),
            name: 'sample.tar.zst',
          ),
          const ArchiveReadOptions(maxContainerDecodeSize: 100),
        ),
        throwsA(isA<SizeLimitExceededException>()),
      );
    });

    test('corruption surfaces as a typed error', () async {
      final bytes = Uint8List.fromList(fixtureBytes('hello.zst'));
      bytes[bytes.length - 6] ^= 0xFF;
      final reader = await const ZstdFormat().openReader(
        MemoryByteSource(bytes),
        const ArchiveReadOptions(),
      );
      await expectLater(
        collect(reader, reader.entries.single),
        throwsA(isA<CorruptArchiveException>()),
      );
      await reader.close();
    });

    test('a non-zstd input does not match', () async {
      expect(
        await const ZstdFormat().matches(
          MemoryByteSource(Uint8List.fromList('not zstd!'.codeUnits)),
        ),
        isFalse,
      );
    });
  });
}
