@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:koni_archive_core/koni_archive_core.dart';
import 'package:koni_zip/koni_zip.dart';
import 'package:test/test.dart';

/// Fixtures generated by `tool/generate_fixtures.dart` with Info-ZIP's
/// zip(1); see test/fixtures/zip/fixtures_manifest.json for provenance.
Uint8List fixtureBytes(String name) =>
    File('test/fixtures/zip/$name').readAsBytesSync();

Future<ArchiveReader> openFixture(String name) => const ZipFormat().openReader(
  MemoryByteSource(fixtureBytes(name)),
  const ArchiveReadOptions(),
);

Future<String> collectString(ArchiveReader reader, ArchiveEntry entry) async =>
    utf8.decode(
      (await reader.openRead(entry).toList()).expand<int>((c) => c).toList(),
    );

/// zip(1) rounded 03:04:05 to the DOS timestamp 03:04:06 (2 s resolution;
/// wall time exposed as UTC — documented lossiness, §8).
final dosMtime = DateTime.utc(2020, 1, 2, 3, 4, 6);

void main() {
  group('stored_basic.zip', () {
    test('lists the full entry model', () async {
      final reader = await openFixture('stored_basic.zip');
      expect(reader.entries.map((e) => e.path), [
        'hello.txt',
        'empty.txt',
        'nested',
        'nested/deep',
        'nested/deep/data.bin',
        '日本語',
        '日本語/ページ001.txt',
      ]);
      final byPath = {for (final e in reader.entries) e.path: e};

      final hello = byPath['hello.txt']!;
      expect(hello.type, ArchiveEntryType.file);
      expect(hello.uncompressedSize, 12);
      expect(hello.compressedSize, 12, reason: 'stored: sizes match');
      expect(hello.compression, ArchiveCompression.stored);
      expect(hello.modified, dosMtime);
      expect(hello.posixMode, int.parse('644', radix: 8));
      expect(hello.crc32, isNotNull);
      expect(hello.isEncrypted, isFalse);

      expect(byPath['nested']!.type, ArchiveEntryType.directory);
      expect(byPath['nested']!.posixMode, int.parse('755', radix: 8));
      expect(byPath['日本語']!.type, ArchiveEntryType.directory);
      expect(byPath['empty.txt']!.uncompressedSize, 0);
    });

    test('streams content with CRC verification', () async {
      final reader = await openFixture('stored_basic.zip');
      final byPath = {for (final e in reader.entries) e.path: e};
      expect(
        await collectString(reader, byPath['hello.txt']!),
        'hello, zip!\n',
      );
      expect(await collectString(reader, byPath['empty.txt']!), '');
      expect(
        await collectString(reader, byPath['日本語/ページ001.txt']!),
        'unicode page\n',
      );
      final data =
          (await reader.openRead(byPath['nested/deep/data.bin']!).toList())
              .expand<int>((c) => c)
              .toList();
      expect(data, List.generate(2600, (i) => (i * 7 + 3) & 0xFF));
    });
  });

  group('EOCD variations (§5)', () {
    test('an archive comment pushes the EOCD off the end', () async {
      final reader = await openFixture('comment.zip');
      expect(reader.entries.single.path, 'hello.txt');
      expect(
        await collectString(reader, reader.entries.single),
        'hello, zip!\n',
      );
    });

    test('a prefixed (SFX-style) archive lists and streams', () async {
      final reader = await openFixture('prefixed.zip');
      expect(reader.entries, hasLength(7));
      final byPath = {for (final e in reader.entries) e.path: e};
      expect(
        await collectString(reader, byPath['hello.txt']!),
        'hello, zip!\n',
      );
      final data =
          (await reader.openRead(byPath['nested/deep/data.bin']!).toList())
              .expand<int>((c) => c)
              .toList();
      expect(data, hasLength(2600));
    });

    test('the canonical empty archive lists no entries', () async {
      final reader = await openFixture('empty.zip');
      expect(reader.entries, isEmpty);
    });

    test('a zip(1) -fz ZIP64 archive lists and streams (M7)', () async {
      final reader = await openFixture('zip64.zip');
      final byPath = {for (final e in reader.entries) e.path: e};
      expect(byPath.keys, contains('nested/deep/data.bin'));
      final data =
          (await reader.openRead(byPath['nested/deep/data.bin']!).toList())
              .expand<int>((c) => c)
              .toList();
      expect(data, List.generate(2600, (i) => (i * 7 + 3) & 0xFF));
    });
  });

  group('entry-scoped typed errors (§9)', () {
    test(
      'encrypted entries are flagged; reading throws; listing works',
      () async {
        final reader = await openFixture('encrypted.zip');
        final entry = reader.entries.single;
        expect(entry.isEncrypted, isTrue);
        expect(
          () => reader.openRead(entry),
          throwsA(
            isA<EncryptedArchiveException>().having(
              (e) => e.entryPath,
              'entryPath',
              'hello.txt',
            ),
          ),
        );
      },
    );

    test(
      'unsupported methods name the method; archive stays readable (§8)',
      () async {
        // No real fixture uses an exotic method; assert via the encrypted
        // fixture path in the test above and the synthetic suite (bzip2 ids
        // etc. are covered there). Here: deflate now DECODES (M5).
        final reader = await openFixture('deflated.zip');
        final byPath = {for (final e in reader.entries) e.path: e};
        final data = byPath['nested/deep/data.bin']!;
        expect(data.compression, ArchiveCompression.deflate);
        expect(data.uncompressedSize, 2600);
        expect(data.compressedSize, lessThan(2600));
        final decoded =
            (await reader.openRead(data).toList())
                .expand<int>((c) => c)
                .toList();
        expect(
          decoded,
          List.generate(2600, (i) => (i * 7 + 3) & 0xFF),
          reason: 'deflate content decodes with CRC verification (M5)',
        );
        expect(
          await collectString(reader, byPath['hello.txt']!),
          'hello, zip!\n',
        );
      },
    );
  });

  group('CBZ deflated (flagship, M5)', () {
    test('a deflated CBZ lists and streams its pages end-to-end', () async {
      final reader = await openFixture('synthetic_comic_deflated.cbz');
      final pages =
          reader.entries.where((e) => e.path.endsWith('.png')).toList();
      expect(pages, hasLength(3));
      for (final page in pages) {
        expect(page.compression, ArchiveCompression.deflate);
        final content =
            (await reader.openRead(page).toList())
                .expand<int>((c) => c)
                .toList();
        expect(content, hasLength(1032));
        expect(content.take(8), [
          0x89,
          0x50,
          0x4E,
          0x47,
          0x0D,
          0x0A,
          0x1A,
          0x0A,
        ]);
      }
    });
  });

  group('CBZ (flagship use case)', () {
    test('a stored CBZ lists and streams its pages', () async {
      final reader = await openFixture('synthetic_comic.cbz');
      final pages =
          reader.entries.where((e) => e.path.endsWith('.png')).toList();
      expect(pages, hasLength(3));
      final first = (await reader.openRead(pages.first).toList()).expand<int>(
        (c) => c,
      );
      expect(first.take(8), [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
      expect(first, hasLength(1032));
    });
  });

  group('detection against fixtures (§5)', () {
    test(
      'every fixture is detected as zip, incl. prefixed and empty',
      () async {
        const format = ZipFormat();
        for (final name in [
          'stored_basic.zip',
          'deflated.zip',
          'comment.zip',
          'prefixed.zip',
          'encrypted.zip',
          'empty.zip',
          'synthetic_comic.cbz',
        ]) {
          final source = MemoryByteSource(fixtureBytes(name));
          expect(await format.matches(source), isTrue, reason: name);
        }
      },
    );

    test('non-zip bytes are rejected', () async {
      const format = ZipFormat();
      expect(
        await format.matches(
          MemoryByteSource(
            Uint8List.fromList(
              List.generate(4096, (i) => (i * 37 + 11) & 0xFF),
            ),
          ),
        ),
        isFalse,
      );
      expect(await format.matches(MemoryByteSource(Uint8List(10))), isFalse);
    });
  });
}
