@TestOn('vm')
library;

import 'dart:io';
import 'dart:typed_data';

import 'package:koni_archive_core/koni_archive_core.dart';
import 'package:koni_bzip2/koni_bzip2.dart';
import 'package:koni_tar/koni_tar.dart';
import 'package:test/test.dart';

/// Fixtures generated by `tool/generate_fixtures.dart` with bzip2(1); see
/// test/fixtures/bzip2/fixtures_manifest.json for provenance.
Uint8List fixtureBytes(String name) =>
    File('test/fixtures/bzip2/$name').readAsBytesSync();

Future<ArchiveReader> openFixture(
  String name, {
  String? sourceName,
  ArchiveReadOptions options = const ArchiveReadOptions(),
  List<ArchiveFormat> layered = const [],
}) => Bzip2Format(
  layeredFormats: layered,
).openReader(MemoryByteSource(fixtureBytes(name), name: sourceName), options);

Future<Uint8List> collect(ArchiveReader reader, ArchiveEntry entry) async {
  final b = BytesBuilder(copy: false);
  await for (final chunk in reader.openRead(entry)) {
    b.add(chunk);
  }
  return b.takeBytes();
}

void main() {
  final hello = fixtureBytes('hello.txt');
  final prose = fixtureBytes('prose.bin');

  group('single-entry .bz2', () {
    test('decodes with unknown size and bzip2 metadata', () async {
      final reader = await openFixture(
        'hello.bz2',
        sourceName: '/downloads/hello.bz2',
      );
      final entry = reader.entries.single;
      expect(entry.path, 'hello');
      expect(entry.type, ArchiveEntryType.file);
      expect(entry.compression, ArchiveCompression.bzip2);
      expect(entry.uncompressedSize, -1, reason: 'bzip2 records no size');
      expect(entry.compressedSize, fixtureBytes('hello.bz2').length);
      expect(entry.modified, isNull);
      expect(await collect(reader, entry), hello);
      await reader.close();
    });

    test('name derivation: .tbz2 -> .tar, none -> data', () async {
      final a = await openFixture('hello.bz2', sourceName: 'book.tbz2');
      expect(a.entries.single.path, 'book.tar');
      await a.close();
      final b = await openFixture('hello.bz2');
      expect(b.entries.single.path, 'data');
      await b.close();
    });
  });

  group('layered .tar.bz2', () {
    test('opens as the inner TAR', () async {
      final reader = await openFixture(
        'sample.tar.bz2',
        sourceName: 'sample.tar.bz2',
        layered: const [TarFormat()],
      );
      expect(reader.format.name, 'tar');
      final names = reader.entries.map((e) => e.path).toList();
      expect(names, containsAll(<String>['hello.txt', 'prose.bin']));
      expect(
        await collect(
          reader,
          reader.entries.firstWhere((e) => e.path == 'prose.bin'),
        ),
        prose,
      );
      await reader.close();
    });

    test('falls back to the single entry when the inner probe fails', () async {
      final reader = await openFixture(
        'hello.bz2',
        sourceName: 'hello.bz2',
        layered: const [TarFormat()],
      );
      expect(reader.format.name, 'bzip2');
      expect(await collect(reader, reader.entries.single), hello);
      await reader.close();
    });
  });

  group('guards and errors', () {
    test('maxEntrySize aborts an over-limit decode', () async {
      final reader = await openFixture(
        'sample.tar.bz2',
        options: const ArchiveReadOptions(maxEntrySize: 100),
        // No layering: the single .bz2 entry (the whole tar) exceeds 100 B.
      );
      await expectLater(
        collect(reader, reader.entries.single),
        throwsA(isA<SizeLimitExceededException>()),
      );
      await reader.close();
    });

    test('maxContainerDecodeSize caps a layered .tar.bz2 at open', () async {
      await expectLater(
        Bzip2Format(layeredFormats: const [TarFormat()]).openReader(
          MemoryByteSource(
            fixtureBytes('sample.tar.bz2'),
            name: 'sample.tar.bz2',
          ),
          const ArchiveReadOptions(maxContainerDecodeSize: 100),
        ),
        throwsA(isA<SizeLimitExceededException>()),
      );
    });

    test('corruption surfaces as a typed error', () async {
      final bytes = Uint8List.fromList(fixtureBytes('hello.bz2'));
      bytes[bytes.length - 6] ^= 0xFF;
      final reader = await const Bzip2Format().openReader(
        MemoryByteSource(bytes),
        const ArchiveReadOptions(),
      );
      await expectLater(
        collect(reader, reader.entries.single),
        throwsA(isA<CorruptArchiveException>()),
      );
      await reader.close();
    });

    test('a non-bzip2 input does not match', () async {
      expect(
        await const Bzip2Format().matches(
          MemoryByteSource(Uint8List.fromList('not bzip2!'.codeUnits)),
        ),
        isFalse,
      );
    });
  });
}
