@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:koni_archive_core/koni_archive_core.dart';
import 'package:koni_sevenz/koni_sevenz.dart';
import 'package:test/test.dart';

/// Fixtures generated by `tool/generate_fixtures.dart` with 7zz; see
/// test/fixtures/sevenz/fixtures_manifest.json for provenance.
Uint8List fixtureBytes(String name) =>
    File('test/fixtures/sevenz/$name').readAsBytesSync();

Future<ArchiveReader> openFixture(String name) =>
    const SevenZFormat().openReader(
      MemoryByteSource(fixtureBytes(name)),
      const ArchiveReadOptions(),
    );

Future<Uint8List> collect(ArchiveReader reader, ArchiveEntry entry) async {
  final builder = BytesBuilder(copy: false);
  await for (final chunk in reader.openRead(entry)) {
    builder.add(chunk);
  }
  return builder.takeBytes();
}

Future<String> collectString(ArchiveReader reader, ArchiveEntry entry) async =>
    utf8.decode(await collect(reader, entry));

/// The data.bin pattern from the fixture script.
List<int> dataBinPattern() =>
    List.generate(100000, (i) => ((i * 7) ^ (i >> 3)) & 0xFF);

final fixedMtime = DateTime.utc(2020, 1, 2, 3, 4, 5);

void main() {
  // The same content tree is archived with each supported primary codec:
  // decoding it correctly proves each chain end-to-end (CRCs are verified
  // by default on every read).
  for (final fixture in [
    'lzma2_solid.7z',
    'lzma2_nonsolid.7z',
    'lzma1.7z',
    'copy.7z',
    'deflate.7z',
  ]) {
    group(fixture, () {
      test('lists the full entry model and streams content', () async {
        final reader = await openFixture(fixture);
        final byPath = {for (final e in reader.entries) e.path: e};
        expect(byPath.keys.toSet(), {
          'hello.txt',
          'empty.txt',
          'nested',
          'nested/deep',
          'nested/deep/data.bin',
          '日本語',
          '日本語/ページ001.txt',
        });
        expect(byPath['nested']!.type, ArchiveEntryType.directory);
        expect(byPath['nested/deep']!.type, ArchiveEntryType.directory);

        final hello = byPath['hello.txt']!;
        expect(hello.type, ArchiveEntryType.file);
        expect(hello.uncompressedSize, 11);
        expect(hello.modified, fixedMtime);
        expect(hello.posixMode, int.parse('644', radix: 8));
        expect(await collectString(reader, hello), 'hello, 7z!\n');

        expect(byPath['empty.txt']!.uncompressedSize, 0);
        expect(await collect(reader, byPath['empty.txt']!), isEmpty);

        expect(
          await collectString(reader, byPath['日本語/ページ001.txt']!),
          'unicode page\n',
        );
        expect(
          await collect(reader, byPath['nested/deep/data.bin']!),
          dataBinPattern(),
        );
        await reader.close();
      });
    });
  }

  group('filter chains (M8)', () {
    test('BCJ x86 + LZMA2 round-trips the program payload', () async {
      // Reproduce the fixture script's PRNG payload.
      final code = <int>[];
      var seed = 12345;
      while (code.length < 50000) {
        seed = (seed * 1103515245 + 12345) & 0x7FFFFFFF;
        if (seed % 7 == 0) {
          code.addAll([
            0xE8,
            seed & 0xFF,
            (seed >> 8) & 0xFF,
            (seed >> 16) & 0x0F,
            0x00,
          ]);
        } else {
          code.add(seed & 0xFF);
        }
      }
      final reader = await openFixture('bcj_lzma2.7z');
      final entry = reader.entries.singleWhere((e) => e.isFile);
      expect(await collect(reader, entry), code);
    });

    test('Delta + LZMA2 round-trips the data payload', () async {
      final reader = await openFixture('delta_lzma2.7z');
      final entry = reader.entries.singleWhere((e) => e.isFile);
      expect(await collect(reader, entry), dataBinPattern());
    });
  });

  group('solid blocks and the LRU cache (§8)', () {
    test(
      'random access into a solid block; repeat reads served from cache',
      () async {
        final reader = await openFixture('lzma2_solid.7z');
        final byPath = {for (final e in reader.entries) e.path: e};
        // Jump straight to a late entry (decodes the folder once)…
        expect(
          await collectString(reader, byPath['日本語/ページ001.txt']!),
          'unicode page\n',
        );
        // …then page-flip around: everything else in the block is cached.
        expect(
          await collectString(reader, byPath['hello.txt']!),
          'hello, 7z!\n',
        );
        expect(
          await collect(reader, byPath['nested/deep/data.bin']!),
          dataBinPattern(),
        );
        await reader.close();
      },
    );
  });

  group('deferred codecs are typed errors; listing still works (§8/§9)', () {
    test('PPMd', () async {
      final reader = await openFixture('ppmd.7z');
      final entry = reader.entries.singleWhere((e) => e.isFile);
      expect(entry.compression.name, 'ppmd');
      expect(
        () => reader.openRead(entry),
        throwsA(
          isA<UnsupportedCompressionException>().having(
            (e) => e.methodName,
            'methodName',
            'ppmd',
          ),
        ),
      );
    });

    test('BCJ2', () async {
      final reader = await openFixture('bcj2.7z');
      final entry = reader.entries.singleWhere((e) => e.isFile);
      expect(
        () => reader.openRead(entry),
        throwsA(
          isA<UnsupportedCompressionException>().having(
            (e) => e.methodName,
            'methodName',
            'bcj2',
          ),
        ),
      );
    });

    // Decryption with a password is covered in sevenz_encryption_test.dart;
    // here we pin the no-password behavior (listing works, reads/opens are
    // typed errors).
    test('AES-encrypted streams throw without a password', () async {
      final reader = await openFixture('encrypted.7z');
      final entry = reader.entries.singleWhere((e) => e.isFile);
      expect(
        () => reader.openRead(entry),
        throwsA(isA<EncryptedArchiveException>()),
      );
    });

    test('AES-encrypted header fails at open without a password', () async {
      await expectLater(
        openFixture('encrypted_header.7z'),
        throwsA(isA<EncryptedArchiveException>()),
      );
    });
  });

  group('CB7 (flagship use case)', () {
    test('a solid CB7 lists and streams its pages', () async {
      final reader = await openFixture('synthetic_comic.cb7');
      final pages =
          reader.entries.where((e) => e.path.endsWith('.png')).toList();
      expect(pages, hasLength(3));
      for (final page in pages) {
        final content = await collect(reader, page);
        expect(content, hasLength(1032));
        expect(content.take(8), [
          0x89,
          0x50,
          0x4E,
          0x47,
          0x0D,
          0x0A,
          0x1A,
          0x0A,
        ]);
      }
      expect(
        await collectString(
          reader,
          reader.entries.singleWhere((e) => e.path.endsWith('.xml')),
        ),
        contains('Synthetic'),
      );
    });
  });

  group('robustness (§7)', () {
    test('every fixture is detected as 7z; noise is rejected', () async {
      const format = SevenZFormat();
      final dir = Directory('test/fixtures/sevenz');
      for (final file in dir.listSync().whereType<File>()) {
        if (!file.path.endsWith('.7z') && !file.path.endsWith('.cb7')) {
          continue;
        }
        expect(
          await format.matches(MemoryByteSource(file.readAsBytesSync())),
          isTrue,
          reason: file.path,
        );
      }
      expect(
        await format.matches(
          MemoryByteSource(
            Uint8List.fromList(List.generate(64, (i) => (i * 37) & 0xFF)),
          ),
        ),
        isFalse,
      );
    });

    test('truncations throw typed errors', () async {
      final bytes = fixtureBytes('lzma2_solid.7z');
      for (final cut in [8, 31, 40, bytes.length ~/ 2, bytes.length - 3]) {
        final sliced = Uint8List.sublistView(bytes, 0, cut);
        Object? error;
        try {
          final reader = await const SevenZFormat().openReader(
            MemoryByteSource(sliced),
            const ArchiveReadOptions(),
          );
          for (final entry in reader.entries) {
            await reader.openRead(entry).toList();
          }
        } on Object catch (e) {
          error = e;
        }
        expect(error, isA<ArchiveException>(), reason: 'cut at $cut');
      }
    });

    test(
      'a corrupted packed stream is a typed error (CRC or decode)',
      () async {
        final bytes = fixtureBytes('lzma2_solid.7z');
        bytes[40] ^= 0xFF; // inside the packed area
        final reader = await const SevenZFormat().openReader(
          MemoryByteSource(bytes),
          const ArchiveReadOptions(),
        );
        // A non-empty entry, so the (damaged) solid block must be decoded.
        final entry = reader.entries.firstWhere((e) => e.path == 'hello.txt');
        await expectLater(
          reader.openRead(entry).toList(),
          throwsA(isA<ArchiveException>()),
        );
      },
    );
  });
}
