@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:koni_archive_core/koni_archive_core.dart';
import 'package:koni_rar/koni_rar.dart';
import 'package:test/test.dart';

/// Fixtures generated by `tool/generate_fixtures.dart` with the RARLAB
/// `rar` tool; see test/fixtures/rar/fixtures_manifest.json for provenance.
Uint8List fixtureBytes(String name) =>
    File('test/fixtures/rar/$name').readAsBytesSync();

Future<ArchiveReader> openFixture(String name) => const RarFormat().openReader(
  MemoryByteSource(fixtureBytes(name)),
  const ArchiveReadOptions(),
);

Future<Uint8List> collect(ArchiveReader reader, ArchiveEntry entry) async {
  final builder = BytesBuilder(copy: false);
  await for (final chunk in reader.openRead(entry)) {
    builder.add(chunk);
  }
  return builder.takeBytes();
}

Future<String> collectString(ArchiveReader reader, ArchiveEntry entry) async =>
    utf8.decode(await collect(reader, entry));

List<int> dataBinPattern() =>
    List.generate(100000, (i) => ((i * 7) ^ (i >> 3)) & 0xFF);

void main() {
  // Store (method 0), Normal (method 3), Best+solid (method 5): the same
  // content tree, decoded via each path with CRC verification on.
  for (final fixture in ['store.rar', 'normal.rar', 'best_solid.rar']) {
    group(fixture, () {
      test('lists the full entry model and streams content', () async {
        final reader = await openFixture(fixture);
        final byPath = {for (final e in reader.entries) e.path: e};
        expect(byPath.keys.toSet(), {
          'hello.txt',
          'empty.txt',
          'nested/deep/data.bin',
          '日本語/ページ001.txt',
          'nested/deep',
          'nested',
          '日本語',
        });
        expect(byPath['nested']!.type, ArchiveEntryType.directory);

        final hello = byPath['hello.txt']!;
        expect(hello.type, ArchiveEntryType.file);
        expect(hello.uncompressedSize, 12);
        expect(hello.crc32, isNotNull);
        expect(await collectString(reader, hello), 'hello, rar!\n');

        expect(await collect(reader, byPath['empty.txt']!), isEmpty);
        expect(
          await collectString(reader, byPath['日本語/ページ001.txt']!),
          'unicode page\n',
        );
        expect(
          await collect(reader, byPath['nested/deep/data.bin']!),
          dataBinPattern(),
          reason: 'the 100 KB compressed payload must decode exactly',
        );
        await reader.close();
      });
    });
  }

  group('solid random access', () {
    test('reading a late entry then an early one both verify', () async {
      final reader = await openFixture('best_solid.rar');
      final byPath = {for (final e in reader.entries) e.path: e};
      // data.bin is late in the solid run; hello.txt is early.
      expect(
        await collect(reader, byPath['nested/deep/data.bin']!),
        dataBinPattern(),
      );
      expect(
        await collectString(reader, byPath['hello.txt']!),
        'hello, rar!\n',
      );
      await reader.close();
    });
  });

  group('CBR (flagship use case)', () {
    test('a compressed CBR lists and streams its pages', () async {
      final reader = await openFixture('synthetic_comic.cbr');
      final pages =
          reader.entries.where((e) => e.path.endsWith('.png')).toList();
      expect(pages, hasLength(3));
      for (final page in pages) {
        final content = await collect(reader, page);
        expect(content, hasLength(1032));
        expect(content.take(8), [
          0x89,
          0x50,
          0x4E,
          0x47,
          0x0D,
          0x0A,
          0x1A,
          0x0A,
        ]);
      }
      await reader.close();
    });
  });

  group('typed errors (§8/§9)', () {
    test('encrypted entries throw at openRead; listing works', () async {
      final reader = await openFixture('encrypted.rar');
      final entry = reader.entries.singleWhere((e) => e.isFile);
      expect(entry.isEncrypted, isTrue);
      expect(
        () => reader.openRead(entry),
        throwsA(isA<EncryptedArchiveException>()),
      );
    });

    test('encrypted headers fail at open, typed', () async {
      await expectLater(
        openFixture('encrypted_headers.rar'),
        throwsA(isA<EncryptedArchiveException>()),
      );
    });
  });

  group('detection and RAR4 (§5/§8)', () {
    test('RAR5 fixtures are detected; noise is rejected', () async {
      const format = RarFormat();
      for (final name in ['store.rar', 'normal.rar', 'synthetic_comic.cbr']) {
        expect(
          await format.matches(MemoryByteSource(fixtureBytes(name))),
          isTrue,
          reason: name,
        );
      }
      expect(
        await format.matches(
          MemoryByteSource(Uint8List.fromList(List.filled(32, 0x00))),
        ),
        isFalse,
      );
    });

    test(
      'a RAR4 signature is detected but opening throws (M10 scope)',
      () async {
        // Rar!\x1A\x07\x00 + junk: recognized as RAR, refused as v4.
        final v4 = Uint8List.fromList([
          0x52,
          0x61,
          0x72,
          0x21,
          0x1A,
          0x07,
          0x00,
          0x00,
          ...List.filled(32, 0),
        ]);
        const format = RarFormat();
        expect(await format.matches(MemoryByteSource(v4)), isTrue);
        await expectLater(
          format.openReader(MemoryByteSource(v4), const ArchiveReadOptions()),
          throwsA(
            isA<UnsupportedFeatureException>().having(
              (e) => e.message,
              'message',
              contains('RAR4'),
            ),
          ),
        );
      },
    );
  });

  group('robustness (§7)', () {
    test('truncations throw typed errors', () async {
      final bytes = fixtureBytes('normal.rar');
      for (final cut in [8, 20, bytes.length ~/ 2, bytes.length - 3]) {
        final sliced = Uint8List.sublistView(bytes, 0, cut);
        Object? error;
        try {
          final reader = await const RarFormat().openReader(
            MemoryByteSource(sliced),
            const ArchiveReadOptions(),
          );
          for (final entry in reader.entries) {
            await reader.openRead(entry).toList();
          }
        } on Object catch (e) {
          error = e;
        }
        // §7 invariant: a truncation either yields a (possibly empty)
        // readable archive or throws a *typed* error — never anything else.
        expect(
          error == null || error is ArchiveException,
          isTrue,
          reason: 'cut at $cut threw ${error.runtimeType}',
        );
      }
    });

    test('a corrupted compressed stream is a typed error', () async {
      final bytes = fixtureBytes('normal.rar');
      // Corrupt bytes inside the largest entry's data area.
      bytes[bytes.length ~/ 2] ^= 0xFF;
      final reader = await const RarFormat().openReader(
        MemoryByteSource(bytes),
        const ArchiveReadOptions(),
      );
      final entry = reader.entries.firstWhere(
        (e) => e.path == 'nested/deep/data.bin',
      );
      await expectLater(
        reader.openRead(entry).toList(),
        throwsA(isA<ArchiveException>()),
      );
    });
  });
}
